### ISSUE TITLE
Maintain picture size

### ISSUE THREAD

**Issue by RidaAyed** [maulasjoumaico/pyqrtopdf#2]
Resize larger paths image size appropriately in order to keep consistency

![img](https://i.imgur.com/rhgtGPP.png)

**Comment by maulasjoumaico** [comment]
Addition of PyQRtoPDF.resize_qr_image(path, basewidth) to resize uniform QR image before attaching to PDF file.

**Comment by ghost** [comment]
Addition of PyQRtoPDF.resize_qr_image(path, basewidth) to resize uniform QR image before attaching to PDF file.
